import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import {  Outfit } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import AppMainLayout from "@/components/AppMainLayout";
import { TeamProvider } from "@/context/TeamContext";
import { TabProvider } from "@/context/TabContext";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });


// const manrope = Manrope({
//   subsets: ["latin"],
//   variable: "--font-manrope",
// });

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${outfit.className} antialiased`}
      >
        <TeamProvider>
          <TabProvider>
            <AppMainLayout>{children}</AppMainLayout>
            <Toaster richColors position="top-right" />
          </TabProvider>
        </TeamProvider>
      </body>
    </html>
  );
}
